from django.urls import path

from .views import (
    average_age,
    busy_doctors,
    contacts,
    diagnosis,
    doctors_by_age_group,
    doctors_by_prescription,
    index,
    latest_medical_record,
    latest_patient,
    long_term_patients,
    nurse_patient_count,
    nurse_presp,
    nurses_by_patient_age,
    patients,
    patients_by_doctor,
    patients_by_nurse_contact,
    patients_by_specialization,
    patients_with_diagnosis,
    patients_with_multiple_doctors,
    patients_with_prescription,
    specialization,
    total,
    total_medical_records,
    unassigned_nurses,
)

urlpatterns = [
    path("", index, name="index"),
    path("diagnosis", diagnosis, name="diagnosis"),
    path("patients", patients, name="patients"),
    path("contacts", contacts, name="contacts"),
    path("total", total, name="total"),
    path("nurse_presp", nurse_presp, name="nurse_presp"),
    path("average_age", average_age, name="average_age"),
    path("latest_patient", latest_patient, name="latest_patient"),
    path("busy_doctors", busy_doctors, name="busy_doctors"),
    path("long_term_patients", long_term_patients, name="long_term_patients"),
    path("nurse_patient_count", nurse_patient_count, name="nurse_patient_count"),
    path("patients_by_doctor", patients_by_doctor, name="patients_by_doctor"),
    path("specialization", specialization, name="specialization"),
    path(
        "patients_by_specialization",
        patients_by_specialization,
        name="patients_by_specialization",
    ),
    path("unassigned_nurses", unassigned_nurses, name="unassigned_nurses"),
    path("latest_medical_record", latest_medical_record, name="latest_medical_record"),
    path(
        "patients_with_diagnosis",
        patients_with_diagnosis,
        name="patients_with_diagnosis",
    ),
    path(
        "doctors_by_age_group",
        doctors_by_age_group,
        name="doctors_by_age_group",
    ),
    path(
        "patients_with_prescription",
        patients_with_prescription,
        name="patients_with_prescription",
    ),
    path(
        "nurses_by_patient_age",
        nurses_by_patient_age,
        name="nurses_by_patient_age",
    ),
    path(
        "total_medical_records",
        total_medical_records,
        name="total_medical_records",
    ),
    path(
        "patients_by_nurse_contact",
        patients_by_nurse_contact,
        name="patients_by_nurse_contact",
    ),
    path(
        "patients_with_multiple_doctors",
        patients_with_multiple_doctors,
        name="patients_with_multiple_doctors",
    ),
    path(
        "doctors_by_prescription",
        doctors_by_prescription,
        name="doctors_by_prescription",
    ),
]
