from django.urls import path

from .views import (
    average_age,
    average_age_by_doctor,
    busy_doctors,
    contacts,
    diagnosis,
    doctor_patient_count,
    doctors_by_admission_date,
    doctors_by_age_group,
    doctors_by_diagnosis_and_age_group,
    doctors_by_diagnosis_and_age_group_names,
    doctors_by_patient_age,
    doctors_by_prescription,
    doctors_with_long_term_patients,
    doctors_with_specific_prescription,
    index,
    latest_medical_record,
    latest_patient,
    long_term_patients,
    nurse_patient_count,
    nurse_patient_count_by_specialization,
    nurse_presp,
    nurses_by_admission_date,
    nurses_by_age_group,
    nurses_by_diagnosis,
    nurses_by_patient_age,
    nurses_by_prescription,
    oldest_patient,
    patients,
    patients_by_age,
    patients_by_doctor,
    patients_by_doctor_and_diagnosis,
    patients_by_doctor_contact,
    patients_by_nurse_contact,
    patients_by_specialization,
    patients_per_month,
    patients_with_diagnosis,
    patients_with_multiple_doctors,
    patients_with_multiple_nurses,
    patients_with_prescription,
    patients_with_specific_prescription,
    specialization,
    total,
    total_medical_records,
    total_patients_by_specialization,
    unassigned_doctor_patients,
    unassigned_doctors,
    unassigned_nurses,
    unassigned_patients,
)

urlpatterns = [
    path("", index, name="index"),
    path("diagnosis", diagnosis, name="diagnosis"),
    path("patients", patients, name="patients"),
    path("contacts", contacts, name="contacts"),
    path("total", total, name="total"),
    path("nurse_presp", nurse_presp, name="nurse_presp"),
    path("average_age", average_age, name="average_age"),
    path("latest_patient", latest_patient, name="latest_patient"),
    path("busy_doctors", busy_doctors, name="busy_doctors"),
    path("long_term_patients", long_term_patients, name="long_term_patients"),
    path("nurse_patient_count", nurse_patient_count, name="nurse_patient_count"),
    path("patients_by_doctor", patients_by_doctor, name="patients_by_doctor"),
    path("specialization", specialization, name="specialization"),
    path(
        "patients_by_specialization",
        patients_by_specialization,
        name="patients_by_specialization",
    ),
    path("unassigned_nurses", unassigned_nurses, name="unassigned_nurses"),
    path("latest_medical_record", latest_medical_record, name="latest_medical_record"),
    path(
        "patients_with_diagnosis",
        patients_with_diagnosis,
        name="patients_with_diagnosis",
    ),
    path(
        "doctors_by_age_group",
        doctors_by_age_group,
        name="doctors_by_age_group",
    ),
    path(
        "patients_with_prescription",
        patients_with_prescription,
        name="patients_with_prescription",
    ),
    path(
        "nurses_by_patient_age",
        nurses_by_patient_age,
        name="nurses_by_patient_age",
    ),
    path(
        "total_medical_records",
        total_medical_records,
        name="total_medical_records",
    ),
    path(
        "patients_by_nurse_contact",
        patients_by_nurse_contact,
        name="patients_by_nurse_contact",
    ),
    path(
        "patients_with_multiple_doctors",
        patients_with_multiple_doctors,
        name="patients_with_multiple_doctors",
    ),
    path(
        "doctors_by_prescription",
        doctors_by_prescription,
        name="doctors_by_prescription",
    ),
    path(
        "unassigned_doctor_patients",
        unassigned_doctor_patients,
        name="unassigned_doctor_patients",
    ),
    path(
        "doctors_by_admission_date",
        doctors_by_admission_date,
        name="doctors_by_admission_date",
    ),
    path("patients_per_month", patients_per_month, name="patients_per_month"),
    path("oldest_patient", oldest_patient, name="oldest_patient"),
    path(
        "nurses_by_admission_date",
        nurses_by_admission_date,
        name="nurses_by_admission_date",
    ),
    path(
        "doctors_by_patient_age",
        doctors_by_patient_age,
        name="doctors_by_patient_age",
    ),
    path("doctor_patient_count", doctor_patient_count, name="doctor_patient_count"),
    path("patients_by_age", patients_by_age, name="patients_by_age"),
    path("nurses_by_diagnosis", nurses_by_diagnosis, name="nurses_by_diagnosis"),
    path("unassigned_doctors", unassigned_doctors, name="unassigned_doctors"),
    path(
        "patients_with_specific_prescription",
        patients_with_specific_prescription,
        name="patients_with_specific_prescription",
    ),
    path(
        "average_age_by_doctor",
        average_age_by_doctor,
        name="average_age_by_doctor",
    ),
    path(
        "doctors_with_specific_prescription",
        doctors_with_specific_prescription,
        name="doctors_with_specific_prescription",
    ),
    path(
        "patients_by_doctor_contact",
        patients_by_doctor_contact,
        name="patients_by_doctor_contact",
    ),
    path(
        "doctors_by_diagnosis_and_age_group",
        doctors_by_diagnosis_and_age_group,
        name="doctors_by_diagnosis_and_age_group",
    ),
    path(
        "nurse_patient_count_by_specialization",
        nurse_patient_count_by_specialization,
        name="nurse_patient_count_by_specialization",
    ),
    path(
        "doctors_by_diagnosis_and_age_group_names",
        doctors_by_diagnosis_and_age_group_names,
        name="doctors_by_diagnosis_and_age_group_names",
    ),
    path(
        "patients_by_doctor_and_diagnosis",
        patients_by_doctor_and_diagnosis,
        name="patients_by_doctor_and_diagnosis",
    ),
    path("nurses_by_age_group", nurses_by_age_group, name="nurses_by_age_group"),
    path(
        "patients_with_multiple_nurses",
        patients_with_multiple_nurses,
        name="patients_with_multiple_nurses",
    ),
    path(
        "total_patients_by_specialization",
        total_patients_by_specialization,
        name="total_patients_by_specialization",
    ),
    path(
        "doctors_with_long_term_patients",
        doctors_with_long_term_patients,
        name="doctors_with_long_term_patients",
    ),
    path(
        "nurses_by_prescription", nurses_by_prescription, name="nurses_by_prescription"
    ),
    path("unassigned_patients", unassigned_patients, name="unassigned_patients"),
]
